# Generated by Django 3.1.4 on 2022-01-03 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appunte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=5000)),
                ('teacher', models.CharField(max_length=100)),
                ('is_pay', models.BooleanField(default=False)),
                ('price', models.CharField(max_length=15)),
                ('published', models.BooleanField(default=False)),
                ('course_pic', models.ImageField(blank=True, upload_to='course_profile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
